### ISSUE TITLE
how to output in stdout ?

### ISSUE THREAD

**Issue by micln** [y0ssar1an/q#33]
thanks ~

**Comment by y0ssar1an** [comment]
Sorry, there's no way to do this. The point of outputting to `$TMPDIR/q` is to isolate just the debug log messages, because stdout is usually quite noisy with normal program output. Adding an stdout option would mean 1. adding a config file, 2. adding an env var, or 3. adding a `q.Stdout()` function. I don't want to do 1 or 2 because I want `q` to stay as a zero-configuration package. I _might_ be persuaded to do 3 if there was a ton of support for it.

The good news is, [if you add `qq()` and `rmqq()` to your shell config](https://github.com/y0ssar1an/q#install) (e.g. `.bash_profile`), it makes it quite easy to read output from `$TMPDIR/q`.

**Comment by micln** [comment]
Great idea!

thanks

**Comment by awkj** [comment]
I think user need simple to stdout ,can't you add a function direct to stdout
example 
 q.S() to stdout
 q.Q() to $TMP
